pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.application' version '9.3.3'
        id 'com.android.library' version '9.3.3'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Velqis"

include ':flags-stub'
include ':vendorcompat'
include ':animationlib'
include ':iconloaderlib'
project(':iconloaderlib').projectDir = new File(rootDir, 'external/systemui-libs/iconloaderlib')
